name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Package
        uses: mstksg/get-package@v1
        with:
          apt-get: portaudio19-dev libjack-dev libasound2-dev portaudio19-dev libmp3lame-dev libsndfile1-dev libportmidi-dev libssl-dev libpulse-dev libfreetype6-dev libfreetype6
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.1.0
      - uses: actions/checkout@v1
      - name: make
        run: make debug
